-- Jalankan di Supabase Dashboard > SQL Editor > New query.
create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  whatsapp text not null,
  location text not null,
  transaction_date date not null default current_date,
  quantity integer not null check (quantity > 0),
  unit_price numeric(14,2) not null check (unit_price >= 0),
  total_price numeric(14,2) not null check (total_price >= 0),
  item_income numeric(14,2) not null check (item_income >= 0),
  created_at timestamptz not null default now()
);
 
alter table public.transactions enable row level security;

-- Mode awal untuk pemakaian pribadi tanpa login: anon dapat membaca/menambahkan data.
-- PENTING: siapa pun yang mengetahui URL + anon key bisa mengakses sesuai policy ini.
-- Untuk data bisnis yang sensitif, aktifkan Supabase Auth dan ganti policy menjadi authenticated.
drop policy if exists "Allow anon read transactions" on public.transactions;
create policy "Allow anon read transactions"
on public.transactions for select to anon using (true);

drop policy if exists "Allow anon insert transactions" on public.transactions;
create policy "Allow anon insert transactions"
on public.transactions for insert to anon with check (true);

grant select, insert on public.transactions to anon;
grant usage, select on sequence public.transactions_id_seq to anon;
