-- Jalankan di Supabase Dashboard > SQL Editor > New query.
-- Konsep aplikasi: catatan penghasilan pribadi. Satu hari boleh memiliki banyak catatan.
create table if not exists public.income_entries (
  id bigint generated by default as identity primary key,
  income_date date not null default current_date,
  source text not null,
  description text default '',
  amount numeric(14,2) not null check (amount >= 0),
  created_at timestamptz not null default now() 
);

alter table public.income_entries enable row level security;

drop policy if exists "Allow anon read income entries" on public.income_entries;
create policy "Allow anon read income entries" on public.income_entries for select to anon using (true);

drop policy if exists "Allow anon insert income entries" on public.income_entries;
create policy "Allow anon insert income entries" on public.income_entries for insert to anon with check (true);

grant select, insert on public.income_entries to anon;
grant usage, select on sequence public.income_entries_id_seq to anon;

-- Ringkasan penghasilan per hari. Opsional, berguna jika nanti ingin mengambil laporan harian langsung dari Supabase.
create or replace view public.daily_income as
select income_date, count(*)::int as entry_count, coalesce(sum(amount),0)::numeric(14,2) as total_income
from public.income_entries
group by income_date
order by income_date desc;
